restrict release workflow to default branch

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -21,6 +21,11 @@ jobs:
       contents: write
       id-token: write
     steps:
+      - if: github.ref_name != github.event.repository.default_branch
+        run: |
+          echo "::error::workflow may only be run with the default branch"
+          exit 1
+
       - uses: rubygems/configure-rubygems-credentials@main
         with:
           role-to-assume: ${{ secrets.RUBYGEMS_OIDC_API_ROLE }}
